import { execSync } from "child_process";
import fs from "fs";
import path from "path";

const root = import.meta.dirname;
const frontendBuildDir = path.join(root, "frontend/build");

// 1. Build frontend
console.log("Building frontend...");
execSync("bash build_frontend.sh", {
  cwd: path.join(root, "frontend"),
  stdio: "inherit",
});

// 2. Read built files and embed as TS constants
console.log("Embedding frontend assets...");

if (!fs.existsSync(frontendBuildDir)) {
  throw new Error(`Frontend build directory not found at ${frontendBuildDir}`);
}

const indexHtmlPath = path.join(frontendBuildDir, "index.html");
if (!fs.existsSync(indexHtmlPath)) {
  throw new Error(`index.html not found at ${indexHtmlPath}`);
}
const indexHtml = fs.readFileSync(indexHtmlPath, "utf8");

function collectFiles(
  dir: string,
  baseDir: string,
  out: Record<string, string>,
): void {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) {
    console.warn(`Directory not found, skipping: ${dir}`);
    return;
  }
  for (const entry of fs.readdirSync(dir)) {
    const fullPath = path.join(dir, entry);
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      collectFiles(fullPath, baseDir, out);
    } else if (stat.isFile()) {
      const key = path.relative(baseDir, fullPath).split(path.sep).join("/");
      out[key] = fs.readFileSync(fullPath, "utf8");
    }
  }
}

const files: Record<string, string> = {};
for (const entry of fs.readdirSync(frontendBuildDir)) {
  if (entry === "index.html") continue;
  const fullPath = path.join(frontendBuildDir, entry);
  const stat = fs.statSync(fullPath);
  if (stat.isDirectory()) {
    collectFiles(fullPath, frontendBuildDir, files);
  } else if (stat.isFile()) {
    files[entry] = fs.readFileSync(fullPath, "utf8");
  }
}

let assetsTs = `// Auto-generated by build.ts — do not edit\n`;
assetsTs += `export const INDEX_HTML = ${JSON.stringify(indexHtml)};\n`;
assetsTs += `export const FILES: Record<string, string> = {\n`;
for (const key of Object.keys(files).sort()) {
  assetsTs += `  ${JSON.stringify(key)}: ${JSON.stringify(files[key])},\n`;
}
assetsTs += `};\n`;

fs.writeFileSync(path.join(root, "frontend/assets.ts"), assetsTs);
console.log("Assets embedded -> frontend/assets.ts");

// 4. Compile single binary from obfuscated bundle
const platform =
  process.platform === "darwin"
    ? "macos"
    : process.platform === "win32"
      ? "windows"
      : "linux";
const arch = process.arch === "arm64" ? "arm64" : "x86_64";

const binaryName = `shinro-analyzer-${platform}-${arch}`;

console.log("Compiling executable...");
execSync(
  `bun build --minify --compile --sourcemap ${path.join(root, "index.ts")} --outfile ${path.join(root, binaryName)}`,
  { stdio: "inherit" },
);
console.log(`Executable built -> ./${binaryName}`);
